name: Debug AWS Credentials

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check AWS Access Key is Loaded
        run: |
          echo "AWS_ACCESS_KEY_ID is set to: ${AWS_ACCESS_KEY_ID}"
          echo "AWS_SECRET_ACCESS_KEY is set."
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
